default source code change to src-jdbc3 for support java 1.5
Caused by: java.lang.NoClassDefFoundError:
java/sql/SQLClientInfoException
==>
java 1.5 下没有SQLClientInfoException,解决办法是log4jdbc要采用src-jdbc3下的源代码
jdbc4以后要求java>=1.6